/* Generated by Lang-0x42A */
/* Warning! Your code is not optimized and runs in virtual machine mode. */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>


#define ARRAY_MAX 64000


int column, parsed;
int arr[ARRAY_MAX];
int arr2[ARRAY_MAX];
int run;
char *source_code;


void VM(const char programm[]){
    memset(arr, 0, sizeof(arr));
    while (run){
        int i = parsed;

        if (programm[i] != 0){
            switch (programm[i]) {
                case '>':   {
                    column++;
                    if (column > ARRAY_MAX){
                        column = 0;
                    }
                    break;
                }
                
                case '<':   {
                    column--;
                    if (column < 0){
                        column = ARRAY_MAX;
                    }
                    break;
                }

                case '+':   {
                    arr[column]++;
                    if (arr[column] > 1024){
                        arr[column] = 0;
                    }
                    break;
                }
                
                case '-':   {
                    arr[column]++;
                    if (arr[column] < 0){
                        arr[column] = 1024;
                    }
                    break;
                }

                case '.':   {
                    putchar(arr[column]);
                    break;
                }
                
                case ',':   {
                    arr[column] = getchar();
                    break;
                }
                
                case 'C':   {
                    memset(arr, 0, sizeof(arr));
                    break;
                }
                
                case '~':   {
                    break;
                }
                
                case 'S':   {
                    memcpy(arr2, arr, sizeof(arr));
                    break;
                }
                
                case 'L':   {
                    memcpy(arr, arr2, sizeof(arr));
                    break;
                }
                
                case 'Q':   {
                    puts(source_code);
                    break;
                }
                
                case 'D':   {
                    break;
                }
                
                case 'E':   {
                    exit(0);
                    break;
                }
                
                case 'J':   {
                    break;
                }
                
                case '$':   {
                    break;
                }
                
                case 'e':   {
                    VM(arr[column]);
                    break;
                }
                
                case 'r':   {
                    break;
                }
                
                case '0':   {
                    arr[column] = 0;
                    break;
                }
                
                case '1':   {
                    arr[column] = 1;
                    break;
                }
                
                case '2':   {
                    arr[column] = 2;
                    break;
                }
                
                case '3':   {
                    arr[column] = 3;
                    break;
                }
                
                case '4':   {
                    arr[column] = 4;
                    break;
                }
                
                case '5':   {
                    arr[column] = 5;
                    break;
                }
                
                case '6':   {
                    arr[column] = 6;
                    break;
                }
                
                case '7':   {
                    arr[column] = 7;
                    break;
                }
                
                case '8':   {
                    arr[column] = 8;
                    break;
                }
                
                case '9':   {
                    arr[column] = 9;
                    break;
                }

                
            }
        }
            
        
    }
    
    
}
/*
Имеет 64000 ячеек памяти

Инструкции языка Ъ:
+ - Увеличить значение в ячейке;
- - Уменьшить значение в ячейке;
> - Перейти на следующую ячейку;
< - Перейти на предыдущую ячейку;
[ - (цикл) если значение текущей ячейки ноль, перейти вперёд по тексту программы на ячейку следующую за соответствующей ] (с учётом вложенности);
] - Конец цикла;
. - Вывод текущей ячейки;
, - Ввод одного символа;
~ - Отладочный символ;
S - Сохранить состояние памяти;
L - Загрузить память;
Q - Вывести исходный код программы;
D - Debug режим;
E - Выход из программы;
C - Очистить память;
$ - Метка, программа перейдет на неё при команде J,
Если метки нет, программа аварийно завершится;
J - Переход на следующую метку;
e - Выполнить команду соответствующую символу в текущей ячейке
r - Записать в ячейку случайное число;
0 - Очищает значение в ячейке;
Число от 1 до 9 - Прибавляет число к текущему значениею в ячейке;
*/

int main(){
    run = 1;
    VM("D++++++++++[~>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.CE");
    return 0;
}